/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c4c7c9",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c1e",
        "on-tertiary-container": "#75ed81",
        "background": "#f9f9fc",
        "on-surface-variant": "#414751",
        "on-primary-container": "#bed7ff",
        "surface-container-low": "#f3f3f6",
        "inverse-surface": "#2f3133",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#434749",
        "on-surface": "#1a1c1e",
        "secondary-fixed": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-container": "#dde0e2",
        "surface-variant": "#e2e2e5",
        "surface-dim": "#dadadc",
        "surface-container-highest": "#e2e2e5",
        "secondary": "#5b5f61",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001c3a",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f0f3",
        "surface-tint": "#075fac",
        "surface-container-high": "#e8e8ea",
        "on-primary-fixed-variant": "#004785",
        "on-secondary-fixed": "#181c1e",
        "on-tertiary-fixed": "#002106",
        "primary": "#004581",
        "primary-fixed-dim": "#a5c8ff",
        "primary-container": "#005daa",
        "tertiary-container": "#006b24",
        "tertiary-fixed": "#83fc8e",
        "surface": "#f9f9fc",
        "on-tertiary-fixed-variant": "#00531a",
        "surface-container": "#eeeef0",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "inverse-primary": "#a5c8ff",
        "on-secondary-container": "#5f6365",
        "tertiary": "#005019",
        "surface-bright": "#f9f9fc",
        "on-error-container": "#93000a",
        "outline-variant": "#c1c6d3",
        "outline": "#727782",
        "tertiary-fixed-dim": "#66df75",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "20px",
        xl: "32px",
        md: "16px",
        base: "4px",
        margin: "24px",
        lg: "24px",
        sm: "8px",
        "container-max": "1440px",
        xs: "4px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
