"""add_patient_demographics_and_report_results

Revision ID: 161f67538f51
Revises: 3a1b2c3d4e5f
Create Date: 2026-08-11 18:49:12.337496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161f67538f51'
down_revision: Union[str, None] = '3a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mrn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referring_physician', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_patient_mrn', ['mrn'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_patient_mrn', type_='unique')
        batch_op.drop_column('medical_history')
        batch_op.drop_column('referring_physician')
        batch_op.drop_column('mrn')
        batch_op.drop_column('contact')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('sex')
        batch_op.drop_column('age')

    op.drop_table('report_results')
    # ### end Alembic commands ###
